require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestDescriptionsController do

  # This should return the minimal set of attributes required to create a valid
  # TestDescription. As you add validations to TestDescription, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestDescriptionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all test_descriptions as @test_descriptions" do
      test_description = TestDescription.create! valid_attributes
      get :index, {}, valid_session
      assigns(:test_descriptions).should eq([test_description])
    end
  end

  describe "GET show" do
    it "assigns the requested test_description as @test_description" do
      test_description = TestDescription.create! valid_attributes
      get :show, {:id => test_description.to_param}, valid_session
      assigns(:test_description).should eq(test_description)
    end
  end

  describe "GET new" do
    it "assigns a new test_description as @test_description" do
      get :new, {}, valid_session
      assigns(:test_description).should be_a_new(TestDescription)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_description as @test_description" do
      test_description = TestDescription.create! valid_attributes
      get :edit, {:id => test_description.to_param}, valid_session
      assigns(:test_description).should eq(test_description)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestDescription" do
        expect {
          post :create, {:test_description => valid_attributes}, valid_session
        }.to change(TestDescription, :count).by(1)
      end

      it "assigns a newly created test_description as @test_description" do
        post :create, {:test_description => valid_attributes}, valid_session
        assigns(:test_description).should be_a(TestDescription)
        assigns(:test_description).should be_persisted
      end

      it "redirects to the created test_description" do
        post :create, {:test_description => valid_attributes}, valid_session
        response.should redirect_to(TestDescription.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_description as @test_description" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestDescription.any_instance.stub(:save).and_return(false)
        post :create, {:test_description => {}}, valid_session
        assigns(:test_description).should be_a_new(TestDescription)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestDescription.any_instance.stub(:save).and_return(false)
        post :create, {:test_description => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_description" do
        test_description = TestDescription.create! valid_attributes
        # Assuming there are no other test_descriptions in the database, this
        # specifies that the TestDescription created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TestDescription.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => test_description.to_param, :test_description => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested test_description as @test_description" do
        test_description = TestDescription.create! valid_attributes
        put :update, {:id => test_description.to_param, :test_description => valid_attributes}, valid_session
        assigns(:test_description).should eq(test_description)
      end

      it "redirects to the test_description" do
        test_description = TestDescription.create! valid_attributes
        put :update, {:id => test_description.to_param, :test_description => valid_attributes}, valid_session
        response.should redirect_to(test_description)
      end
    end

    describe "with invalid params" do
      it "assigns the test_description as @test_description" do
        test_description = TestDescription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestDescription.any_instance.stub(:save).and_return(false)
        put :update, {:id => test_description.to_param, :test_description => {}}, valid_session
        assigns(:test_description).should eq(test_description)
      end

      it "re-renders the 'edit' template" do
        test_description = TestDescription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestDescription.any_instance.stub(:save).and_return(false)
        put :update, {:id => test_description.to_param, :test_description => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_description" do
      test_description = TestDescription.create! valid_attributes
      expect {
        delete :destroy, {:id => test_description.to_param}, valid_session
      }.to change(TestDescription, :count).by(-1)
    end

    it "redirects to the test_descriptions list" do
      test_description = TestDescription.create! valid_attributes
      delete :destroy, {:id => test_description.to_param}, valid_session
      response.should redirect_to(test_descriptions_url)
    end
  end

end
